config/routes.rb
BlogSegu::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"

  root to: "static_pages#home"

  resources :users do
      member do
        get :following, :followers
      end
  end

  resources :microposts do
    resources :comments
end

resources :users do
    resources :comments
end

  resources :comments
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts#,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :users

  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
    

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Blog Tecnologia por Oscar Gonzalez
  </small>
  <nav>
    <ul>
      <li><%= link_to "Facebook",   'http://www.facebook.com/oscar.sgc' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Blog Tecnologia", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Inicio", root_path %></li>
          <li><%= link_to "Ayuda", '/static_pages/about' %></li>
          <% if signed_in? %>
            <li><%= link_to "Usuarios", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Cuenta <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Perfil", current_user %></li>
                <li><%= link_to "Configuraciones", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Cerrar Sesion", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Iniciar Sesion", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Tecnologia</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>